{{- $env := list
  (dict "name" "AUTO_RESUME" "value" (.Values.callbackFetch.autoResume | toString))
  (dict "name" "AUTO_RESUME_DELAY_SECONDS" "value" (.Values.callbackFetch.autoResumeDelaySeconds | toString))
  (dict "name" "FETCH_DELAY_MIN_SECONDS" "value" (.Values.callbackFetch.fetchDelayMinSeconds | toString))
  (dict "name" "FETCH_DELAY_MAX_SECONDS" "value" (.Values.callbackFetch.fetchDelayMaxSeconds | toString))
  (dict "name" "FETCH_TIMEOUT_SECONDS" "value" (.Values.callbackFetch.fetchTimeoutSeconds | toString))
}}
{{- include "bakeoff.service" (dict "svc" .Values.callbackFetch "root" $ "env" $env) }}
