{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mock-services
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ .Values.ingress.middlewareName }}@kubernetescrd
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.callbackFetch.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "bakeoff.name" (dict "svc" .Values.callbackFetch "root" $) }}
            port:
              number: {{ .Values.callbackFetch.port }}
  - host: {{ .Values.approval.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "bakeoff.name" (dict "svc" .Values.approval "root" $) }}
            port:
              number: {{ .Values.approval.port }}
  - host: {{ .Values.shipping.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "bakeoff.name" (dict "svc" .Values.shipping "root" $) }}
            port:
              number: {{ .Values.shipping.port }}
  - host: {{ .Values.fixture.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "bakeoff.name" (dict "svc" .Values.fixture "root" $) }}
            port:
              number: {{ .Values.fixture.port }}
  tls:
  - hosts:
    - {{ .Values.callbackFetch.domain }}
    secretName: {{ .Values.callbackFetch.name }}-tls
  - hosts:
    - {{ .Values.approval.domain }}
    secretName: {{ .Values.approval.name }}-tls
  - hosts:
    - {{ .Values.shipping.domain }}
    secretName: {{ .Values.shipping.name }}-tls
  - hosts:
    - {{ .Values.fixture.domain }}
    secretName: {{ .Values.fixture.name }}-tls
{{- end }}
