{{- $env := list
  (dict "name" "SHIPPING_SUCCESS_RATE" "value" (.Values.shipping.successRate | toString))
  (dict "name" "SHIPPING_TIMEOUT_RATE" "value" (.Values.shipping.timeoutRate | toString))
  (dict "name" "SHIPPING_SERVER_ERROR_RATE" "value" (.Values.shipping.serverErrorRate | toString))
}}
{{- include "bakeoff.service" (dict "svc" .Values.shipping "root" $ "env" $env) }}
